### ISSUE TITLE
Multiple paragraphs in a blockquote appear as one single paragraph

### ISSUE THREAD

**Issue by AlphaGit** [AlphaGit/alphasmanifesto#44]
Problem traced to this rule:

```css
blockquote p {
    font-style: normal;
    display: inline-block;
}
```
